source 'https://rubygems.org'

ENV['RUBY_DEP_GEM_SILENCE_WARNINGS'] = '1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'

# Serializes Active Record models into JSON API compatible responses
gem 'active_model_serializers', '>= 0.10.2'

# Use postgresql as the database for Active Record
gem 'pg', '~> 0.19.0.pre20160810143640'

# Write schema information in rails models
gem 'annotate', '>= 2.7.1'

# Adds sorting capabilities to Active Record through the `position`
gem 'acts_as_list', '>= 0.7.7'

# Changes urls from example.com/blog/1234 => example.com/blog/10-reasons-to-freak-out
gem 'friendly_id', git: 'https://github.com/norman/friendly_id.git', branch: 'master'

# Manages media asset uploads to S3
gem 'carrierwave', git: 'https://github.com/carrierwaveuploader/carrierwave', branch: 'master'
gem 'carrierwave-aws', '~> 1.0'

# Use Puma as the app server
gem 'puma', '~> 3.0'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  gem 'guard', '>= 2.14.0', :require => false
  gem 'guard-minitest', '2.4.5', :require => false
  gem 'rb-fsevent', :require => false
  gem 'wdm', '>= 0.1.0' if Gem.win_platform?
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
